CREATE DATABASE SoftUni

USE SoftUni

GO

CREATE TABLE Towns (
Id INT IDENTITY,
[Name] NVARCHAR(50) NOT NULL

CONSTRAINT PK_Towns
PRIMARY KEY (Id)
)

CREATE TABLE Addresses (
Id INT IDENTITY,
AddressText NVARCHAR(50) NOT NULL,
TownId INT NOT NULL,

CONSTRAINT PK_Addresses
PRIMARY KEY (Id),

CONSTRAINT FK_Town_Addresses
FOREIGN KEY (TownId)
REFERENCES Towns(Id)
)

CREATE TABLE Departments (
Id INT IDENTITY,
[Name] NVARCHAR(50) NOT NULL,

CONSTRAINT PK_Departments
PRIMARY KEY (Id)
)

CREATE TABLE Employees (
Id INT IDENTITY,
FirstName NVARCHAR(50) NOT NULL,
MiddleName NVARCHAR(50),
LastName NVARCHAR(50) NOT NULL,
JobTitle NVARCHAR(50) NOT NULL,
DepartmentId INT,
HireDate DATE ,
Salary DECIMAL(15,2) NOT NULL,
AddressId INT FOREIGN KEY REFERENCES Addresses (Id),

CONSTRAINT PK_Employees
PRIMARY KEY (Id),

CONSTRAINT FK_Employees_Departments
FOREIGN KEY (DepartmentId)
REFERENCES Departments(Id),

CONSTRAINT FK_Employees_Addresses
FOREIGN KEY (AddressId)
REFERENCES Addresses(Id)
)



