CREATE DATABASE OnlineStore

USE OnlineStore

Go

CREATE TABLE Cities (
CityID INT PRIMARY KEY NOT NULL,
[Name] VARCHAR(50) NOT NULL
)

CREATE TABLE Customers (
CustomerID INT PRIMARY KEY NOT NULL,
[Name] VARCHAR(50) NOT NULL,
Birthday DATE NOT NULL,
CityID INT FOREIGN KEY REFERENCES Cities(CityID)
)

CREATE TABLE Orders (
OrderID INT PRIMARY KEY NOT NULL,
CustomerID INT FOREIGN KEY REFERENCES Customers(CustomerId)
)

CREATE TABLE ItemTypes ( 
ItemTypeID INT PRIMARY KEY NOT NULL,
[Name] VARCHAR(50) NOT NULL
)

CREATE TABLE Items (
ItemID INT PRIMARY KEY NOT NULL,
[Name] VARCHAR(50) NOT NULL,
ItemTypeID INT FOREIGN KEY REFERENCES ItemTypes(ItemTypeID) NOT NULL
)

CREATE TABLE OrderItems (
OrderID INT NOT NULL,
ItemID INT NOT NULL

CONSTRAINT PK_Composite_OrderId_ItemID
PRIMARY KEY(OrderId, ItemId),

CONSTRAINT FK_ItemsID
FOREIGN KEY (ItemID) 
REFERENCES Items(ItemID),

CONSTRAINT FK_OrdersID
FOREIGN KEY (OrderID)
REFERENCES Orders(OrderID)
)